config/routes.rb
# NOTE: There are several rewrite rules defined in
# config/initializers/rack_rewrite.rb which run before these routes.
Rails.application.routes.draw do
  get "/", to: redirect("/upcase")

  scope "upcase" do
    root to: "marketing#show"

    use_doorkeeper

    get "the-weekly-iteration", to: "shows#show", id: "the-weekly-iteration"

    scope module: "admin" do
      resources :users, only: [] do
        resource :masquerade, only: :create
      end
      resource :masquerade, only: :destroy
    end

    constraints Clearance::Constraints::SignedIn.new(&:admin?) do
      namespace :admin do
        resources :decks, only: [:new, :create, :show, :index] do
          resources :flashcards, only: [:new, :create, :edit, :update]
          resource :flashcard_preview, only: [:create]
          patch :flashcard_preview, to: "flashcard_previews#create"
        end
      end
    end

    mount RailsAdmin::Engine => "/admin", as: :rails_admin

    namespace :api do
      namespace :v1 do
        resources :exercises, only: [:update]

        post(
          "exercises/:exercise_uuid/status" => "statuses#create",
          as: :exercise_status,
        )

        post(
          "videos/:video_wistia_id/status" => "statuses#create",
          as: :video_status,
        )
      end
    end

    get "/api/v1/me.json" => "api/v1/users#show", as: :resource_owner

    resources(
      :passwords,
      controller: "clearance/passwords",
      only: [:create, :new],
    )
    resource :session, controller: "sessions", only: [:create]

    resources :users, controller: "clearance/users", only: [] do
      resource(
        :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update],
      )
    end

    get "/unsubscribes/:token" => "unsubscribes#show", as: :unsubscribe

    get "/sign_in" => "sessions#new", as: "sign_in"
    delete "/sign_out" => "sessions#destroy", as: "sign_out"

    resources :clips, only: [] do
      resource :download, only: [:show]
    end

    resources :decks, only: [:show, :index] do
      resources :flashcards, only: [:show]
      resource :results, only: [:show]
    end

    resources :flashcards, only: [] do
      resources :attempts, only: [:create, :update]
    end

    resources :exercises, only: [] do
      resource :trail, controller: "exercise_trails", only: [:show]
    end

    get "/about-us", to: "pages#show", id: "about_us"
    get "/pages/:id", to: "high_voltage/pages#show", as: :page, format: false
    get "/privacy", to: "pages#show", as: :privacy, id: "privacy"
    get "/purchases/:lookup", to: "pages#show", id: "purchase-show"
    get "/terms", to: "pages#show", as: :terms, id: "terms"
    get "/pages/welcome", to: "pages#show", as: "welcome"
    get "/pre-sales/python", to: "pages#show", id: "pre_sale_python"

    resources :repositories, only: [:index] do
      resource :collaboration, only: [:create]
    end

    get(
      ":id" => "repositories#show",
      as: :repository,
      constraints: SlugConstraint.new(Repository),
    )

    resource :search, only: [:show, :create]

    get(
      ":id" => "shows#show",
      as: :show,
      constraints: SlugConstraint.new(Show),
    )

    get "/teams", to: "teams#new"
    resource :team, only: :edit

    resources :invitations, only: [:create, :destroy] do
      resources :acceptances, only: [:new, :create]
    end
    resources :memberships, only: [:destroy]

    get "/trails/completed" => "completed_trails#index", as: :completed_trails

    get(
      ":id" => "trails#show",
      as: :trail,
      constraints: SlugConstraint.new(Trail),
    )

    get "/sign_up" => "users#new", as: :sign_up

    get "/my_account" => "users#edit", as: "my_account"
    patch "/my_account" => "users#update", as: "edit_my_account"

    resources :users, controller: "users" do
      resources :notes, only: [:create, :edit, :update]
      resource(
        :password,
        controller: "passwords",
        only: [:create, :edit, :update],
      )
    end
    resources :passwords, controller: "passwords", only: [:create, :new]

    get "/vanity" => "vanity#index"
    get "/vanity/participant/:id" => "vanity#participant"
    post "/vanity/complete"
    post "/vanity/chooses"
    post "/vanity/reset"
    post "/vanity/add_participant"
    get "/vanity/image"

    resources :videos, only: [:show] do
      resource :auth_to_access, only: [:show]
      resource :twitter_player_card, only: [:show]
      resources :completions, only: [:create], controller: "video_completions"
    end

    resource :forum_sessions, only: :new
    resources :onboardings, only: :create
    get "forum", to: redirect("https://forum.upcase.com"), as: "forum"

    resources(
      :design_for_developers_resources,
      path: "design-for-developers-resources",
      only: [:index, :show],
    )
    resources(
      :test_driven_rails_resources,
      path: "test-driven-rails-resources",
      only: [:index],
    )

    get "/practice" => "practice#show", as: :practice
    get "sitemap.xml" => "sitemaps#show", as: :sitemap, format: "xml"
    get ":id" => "topics#show", as: :topic
    get "/auth/:provider/callback", to: "auth_callbacks#create"
  end
end

app/models/video.rb
class Video < ApplicationRecord
  extend FriendlyId

  include PgSearch::Model
  multisearchable against: [:name, :summary, :notes], if: :search_visible?

  belongs_to :watchable, polymorphic: true, optional: true
  has_many :classifications, as: :classifiable, dependent: :destroy
  has_many :markers, dependent: :destroy
  has_many :statuses, as: :completeable, dependent: :destroy
  has_many :teachers, dependent: :destroy
  has_many :topics, through: :classifications
  has_many :users, through: :teachers
  has_one :step, as: :completeable, dependent: :destroy
  has_one :trail, through: :step

  validates :published_on, presence: true
  validates :slug, presence: true, uniqueness: true
  validates :name, presence: true
  validates :wistia_id, presence: true

  delegate :name, to: :watchable, prefix: true
  delegate :download_url, to: :clip

  friendly_id :name, use: [:slugged, :finders]

  paginates_per 16

  def self.ordered
    order('position asc')
  end

  def self.published
    where('published_on <= ?', Time.zone.today)
  end

  def self.recently_published_first
    order('published_on desc')
  end

  def clip
    @video ||= Clip.new(wistia_id)
  end

  def title_card_image
    if part_of_trail?
      trail.title_card_image
    else
      Trail::DEFAULT_IMAGE_URL
    end
  end

  def has_notes?
    notes.present?
  end

  def summary_or_notes
    summary.presence || notes
  end

  def watchable
    super || step.try(:trail)
  end

  def to_param
    slug
  end

  def part_of_trail?
    trail.present?
  end

  def search_visible?
    if part_of_trail?
      trail.published?
    else
      true
    end
  end

  def state_for(user)
    statuses.most_recent_for_user(user).state
  end

  def published?
    if part_of_trail?
      trail.published?
    else
      published_on <= Date.current
    end
  end

  def update_duration(duration = nil)
    if duration.present?
      update(length_in_minutes: duration)
    else
      VideoDurationUpdater.update_duration(self)
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show
    @video = Video.find(params[:id])
    @watchable = @video.watchable

    respond_to do |format|
      format.html { render_or_redirect }
    end
  end

  private

  def render_or_redirect
    if params[:id] != @video.slug
      redirect_to video_path(@video.slug), status: :moved_permanently
    else
      render
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
  def topic_slugs(object)
    if topic = object.topics.first
      topic.slug.parameterize
    end
  end
end

app/views/videos/_access_callout.html.erb
<div class="access-callout auth-to-access">
  <p><%= t("videos.show.auth_to_access_without_preview_callout_text") %></p>

  <%= auth_to_access_button(video, cta_text: t("videos.show.auth_to_access_button_text")) %>
</div>

app/views/videos/_comments.html.erb
<div id="discourse-comments"></div>
<% unless Rails.env.test? %>
  <script type="text/javascript">
    var discourseUrl = "<%= Forum.url %>";
    var discourseEmbedUrl = "<%= video_url(video) %>";

    (function() {
      var d = document.createElement("script"); d.type = "text/javascript"; d.async = true;
        d.src = discourseUrl + "javascripts/embed.js";
      (document.getElementsByTagName("head")[0] || document.getElementsByTagName("body")[0]).appendChild(d);
    })();
  </script>
<% end %>

app/views/videos/_download_link.html.erb
<a class="button-mini download <%= download_type %>"
  href="<%= clip_download_path(clip.wistia_id, download_type: download_type) %>">
  <%= size_display %>
</a>

app/views/videos/_preview_clip_or_image.html.erb
<div class="title-card">
  <div class="title-card__filter">
    <%= image_tag video.title_card_image, class: "title-card__image" %>
  </div>
</div>

app/views/videos/_seek_buttons.html.erb
<div class="seek-button-template">
  <button class="seek-marker">
    <%= t(".jump-to-topic-in-video") %>
  </button>
</div>

<% content_for :javascript do %>
  <script type="text/javascript">
    $(function() {
      var markers = <%= raw markers.to_json %>;

      var scrollPageToShowVideo = function() {
        $(".wistia-wrapper").get(0).scrollIntoViewIfNeeded();
      };

      var setUrlHashToSectionAnchor = function(anchor) {
        window.location.hash = anchor;
      };

      var bindClickToSeek = function(seekButton, marker) {
        seekButton.on("click", function(event) {
          wistiaEmbed.time(marker.time);
          setUrlHashToSectionAnchor(marker.anchor);
          scrollPageToShowVideo();
          wistiaEmbed.play();
          return false;
        });
      };

      var headerForAnchorId = function(anchor) {
        var specialCharacters = /(\W)/g;
        var escapedAnchorString = anchor.replace(specialCharacters, "\\$1" );
        return $("#" + escapedAnchorString);
      }

      var attachSeekButton = function(marker) {
        var headerForMarker = headerForAnchorId(marker.anchor);
        var seekButton = $(".seek-button-template button").clone();
        bindClickToSeek(seekButton, marker);
        headerForMarker.append(seekButton);
      };

      markers.forEach(attachSeekButton);
    });
  </script>
<% end %>

app/views/videos/_video.html.erb
<figure class="tile weekly-iteration <%= topic_slugs(video) %> <%= video.status_class %>">
  <div class="video-overview title-tags">
    <%= link_to video_path(video) do %>
      <h1 class="video-text"><%= video.name %></h1>

      <p class="video-length" data-wistia-id="<%= video.clip.wistia_id %>">
        <%= video.length_in_minutes %> minutes
      </p>
    <% end %>

    <div class="video-tags">
      <%= render video.topics %>
    </div>
  </div>

  <div class="video-overview hosts">
    <div class="hosts-copy">
      <small class="hosted-by">Hosted by</small>
      <h3 class="teacher-names"><%= teacher_names(video.teachers) %></h3>
    </div>

    <div class="hosts-images">
      <%= render video.teachers %>
    </div>
  </div>

  <p class="description">
    <%= truncate_html(video.summary_or_notes, length: 250) %>
  </p>
</figure>

app/views/videos/_video_player.html.erb
<span class="divider">
  <h4 class="text">Video</h4>
</span>

<div class="video-player">
  <%= render video.clip %>

  <div class="actions">
    <%= render "clips/download_links", clip: video.clip %>

    <div class="mark-as-complete">
      <%= form_tag video_completions_path(video) do %>
        <%= submit_tag t("videos.show.mark-as-complete"), class:"small-button" %>
      <% end %>
    </div>
  </div>
</div>

<% if video.part_of_trail? %>
  <%= render "trails/progress",
    trail: TrailWithProgress.new(
      video.trail,
      user: current_user,
      status_finder: StatusFinder.new(user: current_user),
    )
  %>
<% end %>

app/views/videos/_video_player_placeholder.html.erb
<span class="divider">
  <h4 class="text">Video</h4>
</span>

<div class="video-player">
  <%= render "videos/access_callout", video: video %>
  <%= render "preview_clip_or_image", video: video %>
</div>

app/views/videos/show.html.erb
<% render "shared/content_specific_head_tags", content: @video, type: "video" %>

<% if @video.preview_wistia_id? %>
  <% content_for :head do %>
    <%= render "twitter_player_cards/meta", video: @video %>
  <% end %>
<% end %>

<% content_for :subject_block do %>
  <header class="page-header">
    <h1 class="page-header__title"><%= @video.name %></h1>
    <h2 class="parent-collection">
      <%= link_to @video.watchable_name, @video.watchable %>
    </h2>
    <% if @video.length_in_minutes %>
      <h3 class="page-header__time-to-complete">
        <%= completion_time(@video.length_in_minutes) %>
      </h3>
    <% end  %>
  </header>
<% end %>

<% if signed_in? %>
  <%= render "video_player", video: @video %>
<% else %>
  <%= render "video_player_placeholder", video: @video %>
<% end %>

<% if @video.has_notes? %>
  <div class="text-box">
    <section class="video-notes">
      <header class="video-notes-header">
        <h3>Notes</h3>
      </header>

      <div class="video-notes-content">
        <%= format_markdown(@video.notes) %>
      </div>
    </section>
  </div>
<% end %>

<% if @video.published? %>
  <%= render "comments", video: @video %>
<% end %>

<% if signed_in? %>
  <%= render "seek_buttons", markers: @video.markers %>
<% end %>